### PR TITLE
iOS 13's dark mode support + bug fixes

### PR DESCRIPTION
**Pull request by vincentneo**
as the title says...

Did up some new iconography too. (should match watch os app better too)

Probably best to only merge after Xcode 11 goes stable. (still in beta right now)

### CODE REVIEW

**Comment by vincentneo** [comment]
UPDATE: bugs identified

- Core Data action sheet closes right after appearing. (appears to be this [issue](https://stackoverflow.com/questions/57060606/uiwindow-not-showing-over-content-in-ios-13))
- When switching appearance modes, overlay color does not change automatically.

**Comment by vincentneo** [comment]
Fixed the Core Data iOS 13 action sheet issue!

**Comment by vincentneo** [comment]
I believe the issue here would be the "Open In" issue. 
In my testing, app store version has the issue as well, though i only have one device to test for the time being, and am not sure if this sideloaded version interferes with the app store one on this issue, though that wasn't an issue before iOS 13.

Moreover, its already iOS 13 GM + a few days to official release and such issues exists...

**Comment by merlos** [comment]
@vincentneo Once this is merged, I will proceed to upload the new version to the App store.

**Comment by vincentneo** [comment]
@merlos I was waiting for #129 response, else I think its time for the merge.
Personally tested to be working though.

Note: Another thing is that now it seems that the poly line overlay is now rendered together with the tiles, if the tiles were unavailable, the polyline would not show unlike in before iOS 13. This is most apparent using OpenStreetMap as it takes a while for an uncached loading. Also, if the polyline intercepts with a rail line of Apple Maps, it renders oddly. Noticed this a few days ago, but believe its just another unfixable iOS 13 quirk, just like the private "Apple Maps" logo in the bottom left corner.

**Comment by merlos** [comment]
Sure, no rush.

**Comment by vincentneo** [comment]
@merlos It has been more than a week since my last message in #129. 
Maybe we should go through with the merge, considering no responses? What do you think?

**Comment by merlos** [comment]
Hi @vincentneo, sorry for the delays in answering lately. 

I think we can merge this branch. That issue is not caused by dark mode support but by iOS13 update.

Ont top of what you mention about the tracked line, I also noticed that in iOS 13 user can zoom much more, however OSM has only tiles till certain level. 

I believe both issues seem critical enough to be researched before publishing the new version.

**Comment by vincentneo** [comment]
@merlos,
In this case, I will merge this branch, and fixes for the issues that you've mention can go with further pull requests.

**Pull request merged**
