### PR TITLE
Add localization support

### PR DESCRIPTION
**Pull request by nitricware**
Thanks for creating this awesome app! I translated it to make it accessible to even more users. 

There are some things to consider:

1. The "Reset" and "Save" button now shrink their label based on the length of the word. This causes longer (and therefor smaller) words to appear slightly below the center of the button.
2. I had to translate "Reset" and "Save" slightly different than I wanted in the first place (because the german words were too long):
    * "Reset" is translated to "Löschen" (="Delete") instead of "Zurücksetzen"
    * and "Save" is translated to "Sichern" (="Secure" but also "Save")
3. All future strings should not be hard coded but loaded with ```NSLocalizedString(key, comment)```
4. Strings in the watch interface exist in the .strings file for the storyboard and in the general Localizable.strings and should somewhat match...

I hope you consider merging my pull request and add even more languages.

### CODE REVIEW

**Comment by vincentneo** [comment]
Looks interesting, and if @merlos like it too, may be I'll do up one for Chinese language in future.

Side note however:  
- Have yet to test, only looked at code
- Looks a little messy with `NSLocalizedString(key, comment)`, and with that I fear that in future, a mistyped key would make clumsy collaborators like me be confused. Is it possible for some other alternate implementations with say, the use of extension and enum?

**Comment by merlos** [comment]
Cool @nitricware! Thanks for the support and the translations. It looks pretty good! 🥇 

I´ll try to test the code during the weekend and also add the translation into Spanish and maybe French. 

@vincentneo Chinese is welcome too 👍 

If you want, I think it will be helpful for the user if you could also translate the App Store text

-------------------------
Create GPS traces with waypoints. Offline map support, no time restrictions, no ads, no in-app-purchases.

Open GPX Tracker is ideal for:
* Traveling and vacation (offline map app)
* Collecting and sharing track and waypoints data
* Creating routes and waypoints for editing Open Street Map
* Publishing Open Street Map Traces
* Creating real GPX files for testing your iOS apps in Xcode

Main Features:
* Apple Watch App support
* Offline maps of browsed areas
* Load saved sessions and continue tracking
* Auto recovery last session after crash or closing the app
* Display tracking information in a map
* Display speed, distance, coordinates and time
* Use multiple map sources (Apple Maps, Open Street Maps, CartoDB)
* Pause / Resume tracking
* Add waypoint to user location
* Add waypoint to any place in the map with a long press
* Edit waypoint name
* Drag & Drop waypoint pin
* Remove waypoints
* Share and send GPX files

Please note:
Continued use of GPS running in the background can dramatically decrease battery life.
-------------------------------------
 

@vincentneo in my experience with i18n the way it was implemented by @nitricware is the common one. If the key does not have a translation in current language the default language is displayed, and if the key does not exist it should be easy to detect during development - I don´t remember the exact iOS behavior, but it may display the key or something like that).

**Comment by nitricware** [comment]
Awesome!
Gracias, Merci, Xie Xie, Thanks!

> I don´t remember the exact iOS behavior, but it may display the key or something like that

Yes, it does.

> If you want, I think it will be helpful for the user if you could also translate the App Store text

Sure thing:

Erstellt GPS Pfade mit Wegpunkten. Offline Karten, keine zeitlichen Beschränkungen, keine Werbung, keine In-App-Käufe.

Open GPX Tracker eignet sich ideal für:
* Reisen und Urlaub (offline Karten)
* Wegpunkte sammeln und teilen
* Wegpunkte und Strecken sammeln um Open Street Map zu bearbeiten
* Open Street Map Traces veröffentlichen
* Echte GPX Dateien zum Testen Deiner iOS Apps in Xcode erstellen.

Hauptfeatures:
* Apple Watch Unterstützung
* Offline Karten der angeschauten Gegenden
* Gespeicherte Sitzungen laden und Tracking wiederaufnehmen
* Automatische Wiederherstellung der Sitzung nach einem Crash der App
* Trackinginformation in der App ansehen
* Geschwindigkeit, Distanz, Koordinaten und Zeit anzeigen
* Mehrere Karten-Quellen verwenden (Apple Maps, Open Street Maps, CartoDB)
* Tracking pausieren/fortsetzen
* Wegpunkt zur aktuellen Position hinzufügen
* Wegpunkt zu einer beliebigen Position hinzufügen durch langes Gedrückthalten
* Wegpunkt-Namen bearbeiten
* Drag-und-Drop des Wegpunkt-Pins
* Wegpunkte entfernen
* GPX Dateien teilen und versenden

## Wichtig: Dauerhaftes abfragen des GPS Standortes im Hintergrund kann die Batterielaufzeit drastisch verkürzen.

**Comment by nitricware** [comment]
*Important:* I appended myself to the contributors list in about.html - however I used my twitter handle which is - unfortunately - different from my GitHub handle. I linked to my GitHub profile however. Please change it to whichever style you intended!

**Comment by vincentneo** [comment]
Added a commit as it appears that the Localizable.strings file for the iOS scheme was set as absolute path. This changes it to be relative to group.

I have also set the scheme language back to system defaults.

**Comment by vincentneo** [comment]
>  I used my twitter handle which is - unfortunately - different from my GitHub handle. 

My twitter handle is different from GitHub too, which @merlos used my GitHub one, as probably it didn't make much sense for the handle to be of twitter, but links to GitHub.

I'll leave it to @merlos for this though.

**Comment by merlos** [comment]
Danke @nitricware :). Your name had to be added to the "hall of fame" :) so thanks also for saving us the time.

@vincentneo feel free to use whatever link you prefer. I just used github because it is usually the only way to provide a link when someone sends a PR.

**Comment by merlos** [comment]
As now we will have support for any language I started documenting how to translate open gpx tracker (still work in progress). 

The idea is to add a link in the README of the project and also in about.html 

https://github.com/merlos/iOS-Open-GPX-Tracker/wiki/How-to-translate-Open-GPX-Tracker-into-my-language%3F

**Comment by nitricware** [comment]
> Your name had to be added to the "hall of fame"

Thanks! I'm happy I could help. If you need any strings translated into German in the future, don't hesitate to ask me. You find me on GitHub (obviously) and Twitter (@nitric_ware)

**Comment by vincentneo** [comment]
@nitricware, I was trying to do some testings, and also starting on my Chinese translations, when I've noticed that the Core Data recovery alerts weren't translated. 

Would you mind translating to German for those recovery alert messages? They can be found in function `crashFileRecovery()` of `CoreDataHelper`

Thank you!

**Comment by nitricware** [comment]
Sure thing! I‘ll do it within the coming week!

**Comment by vincentneo** [comment]
Have added my Chinese (Simplified) Translations. 
From what I know, there are some vocabulary changes between Chinese (Simplified) and Chinese (Traditional), but other than that most other characters are usually just a character change,

As I am based in Singapore, I have only been trained Chinese (Simplified) from young, and know only a bit of Chinese (Traditional), which may hinder process on the Chinese (Traditional) translations, as I need to search up on it to ensure accuracy. At least spoken language is the same. 

Also, it seems like Apple Watch app's localizations isn't working? I can only test from simulator, and it does not seem to change, e.g: COORDINATES is still COORDINATES.

**Comment by vincentneo** [comment]
制造卫星导航记录。 线下也可使用的地图，没时间限制，无添加广告，也无需付费。

Open GPX Tracker 适合：
- 旅行 (可以在线下使用)
- 收集和分享定位航点记录
- 制造 Open Street Map 可使用的定位文件
- 可以上窜到 Open Street Map
- 制造真实的 GPX 文件，适合在 Xcode 开发的 iOS app, 测试是否定位设计可以使用

主要功能包括：
- 有 Apple Watch 版本
- 可在线下情况下，继续浏览或记录 GPX 文件
- 可继续记录之前储存的 GPX 文件
- 在 app 死机或意外关上 app 的情况下，app 有恢复功能，可让记录恢复
- 可显示目前定位资料在地图上
- 可显示目前速度，行驶距离，地理坐标, 行驶时间
- 可使用多种地图图像（Apple Maps, Open Street Maps, CartoDB）
- 在记录时，也可以随时继续或暂停
- 可在目前地点或长按地图位置记录为航点
- 可以更改航点名
- 可轻松更改航点位置，拖和搬到新位置就可完成
- 航点也可以被删除
- 简单分享和发送 GPX 文件

**Comment by nitricware** [comment]
> Also, it seems like Apple Watch app's localizations isn't working? I can only test from simulator, and it does not seem to change, e.g: COORDINATES is still COORDINATES.

Did you localize the Storyboard too? That was what I overlooked.
Bildschirmfoto 2019-08-26 um 14 47 22

**Comment by vincentneo** [comment]
Oh no, there seems to be another branch that holds the Spanish and Chinese translations. I was wondering why my Chinese translation commits didn’t show up here. It seems like I have pushed my commits towards that branch too, that’s why. Hope merging won’t be hard next time... (branch nitricware-german_localization)

By the way, I have yet got the time to check for the storyboard stuff, and probably wouldn’t have for the next couple of days, sorry!

**Comment by nitricware** [comment]
> (branch nitricware-german_localization)

Did I do that? :/

**Comment by vincentneo** [comment]
I think @merlos created that branch 😄

Maybe merging this branch to that branch, then merging that branch to the main branch would work?

**Comment by merlos** [comment]
Is it working for you in the Apple Watch? 

For me it is working partially. It seems that it is not getting the labels of the `Interface.strings`

**Comment by nitricware** [comment]
IMG_3969
IMG_3970

It works for me :/

**Comment by vincentneo** [comment]
Interesting, as it still doesn't work for me either.
I assume it would work if tested on a real device, but not in a simulated and forced language selection environment?
@nitricware, was yours tested on device or simulator?

**Comment by nitricware** [comment]
it's on a real device.
Have you cleaned your build folder?

**Comment by merlos** [comment]
I don't know you, but I am not able to set the locale properly on the Apple Watch simulator, neither using Edit schema, nor using the watch application. In the Phone simulator I can...

image

image

image

Then, in the Apple Watch device, cloning and running nitricware german_localization branch (https://github.com/nitricware/iOS-Open-GPX-Tracker/tree/german_localization) works as expected, that is, except the strings that are managed on the controller I get the German translation... so I guess in one of the commits afterwards there may be an issue... and my guts say that it may be related with using `Localizable.strings` and `Interface.strings` at the same time or something like that, as in this repo's branch (https://github.com/merlos/iOS-Open-GPX-Tracker/tree/nitricware-german_localization) in the Apple Watch device I can only see the strings of `Localizable.strings`

**Comment by nitricware** [comment]
Hm :/ what do you suggest?

**Comment by vincentneo** [comment]
> Have you cleaned your build folder?

@nitricware yes I did for each build after changing the scheme settings.

I do not have an Apple Watch to test, so its only simulator for me. Both branches fail to work for me in the case of the watch localisation, but the iOS app does work for both device and simulator.

>  so I guess in one of the commits afterwards there may be an issue... 

@merlos I have remembered toggling the target membership of the lnterface.strings file back when the simulator language change didn't work for me. I may or may not have committed that, but if I did, that may have broke something.

Have read here, that apparently it is a valid issue that the simulator scheme language change does not work for apple watch apps since Xcode 7 era.
https://stackoverflow.com/questions/34103580/can-i-change-the-apple-watch-simulator-language

**Comment by merlos** [comment]
This is weird... I went commit by commit to try to find out which commit introduced the issue changing nothing, cleaning the build folder and running the app in the watch device... and it worked on each commit...

👎  to Apple. Seriously, Apple Watch development is poor... Slow, and as we can see buggy.

**Comment by merlos** [comment]
It seemed that everything worked. So, I merged the changes.

Thanks @nitricware and @vincentneo

**Comment by nitricware** [comment]
Awesome!
This was my very first Open Source Contribution by the way. Thanks for the warm welcome! I'll keep my fork in case I can contribute anything else.

**Pull request merged**
