### PR TITLE
fix #115. User position arrow error upon rotating map 

### LINKED ISSUE #115: User position arrow error upon rotating map.
When user rotates the map the arrow that indicates the direction the phone is pointing is wrong.

**Steps**

1. Open the iOS compass app and make the phone face North 
2. Now, open the tracker and rotate the map.
3. While rotating the map, the arrow should be following the North arrow of the compass in the map. 

**Expected behavior**
When the phone is facing North and the map is rotated user location arrow should point the same direction as the compass red arrow displayed in the map.

### PR DESCRIPTION
**Pull request by merlos**

### CODE REVIEW

**Comment by vincentneo** [comment]
I have added a `UIRotationGestureRecognizer` to make the map rotation's influence on the heading arrow, realtime.

Do check if there is any flaws with the implementation. If not, we can merge this.

**Comment by merlos** [comment]
Cool... I was not able to find a rotation  callback on my research...

Is it possible to move the code of handling the rotation gesture  the GPXMapView?

**Comment by vincentneo** [comment]
Actually, MapKit itself doesn't really have any callbacks for rotation. (I believe) https://github.com/merlos/iOS-Open-GPX-Tracker/pull/116/commits/6f12056fe3232ae45cdb69df7785500d9143bba8 simply uses the "change of region" callbacks from MapKit.

It simply calls `updateHeading()` on end of region change, as the `camera.heading` value is changed.

Got to say that those callbacks are quite rudimentary, with a start, when changing, and end callbacks only, which prompted me to use the rotation gesture. (not sure of another better way of dealing with this.)

I did try to move the rotation gesture to `GPXMapView`, even trying inheriting it to `UIGestureRecognizerDelegate`. Regardless, `rotationGestureHandling(_:)` never seemed to be called. 
To the best of my knowledge, I don't think it's possible. (Or it could just be my lack of knowledge? 😅)

**Comment by vincentneo** [comment]
Time and time again, it has been proven that my skills definitely needs huge improvements 😞.

That is because, it seems like the move to `GPXMapView` does work.

Anyway, I found a new problem, where the gesture does not callback when user stopped interaction, but velocity of the rotation caused the view to continue rotating. In that instance, the heading arrow would be wrong till it fully stops (it is corrected by regionDidChangeAnimated in delegate)

**Comment by merlos** [comment]
Thanks @vincentneo. Don´t be so hard with yourself and enjoy the learning experience :)

**Pull request merged**
