### PR TITLE
Share from ViewController

### PR DESCRIPTION
**Pull request by yoiang**
Hello! This PR accomplishes #46 in a simple manner, adding a Share button to `ViewController`.

This PR is one of two options, I've also created a PR (#52) that instead adds a Share button into the UIAlertController in the Files Table.

### CODE REVIEW

**Comment by merlos** [comment]
@yoiang It looks awesome. Thanks for sharing.

I like the idea of sharing the map either when you are in the list of files or in the map. Shall I use any particular version of GPXActivityItemProvider?

Do you know why when it is saved into iCloud, it does not keep the name of the original file?

Thanks!! Again!

**Comment by yoiang** [comment]
My pleasure! 

The version without the fileName requirement is most flexible and at the end of the day the ItemProvider is just an Item provider, it makes more sense to only expect to provide that ;)

However that might have something to do with the name change, can you show me the flow you're using to save it to iCloud?

**Comment by merlos** [comment]
Thanks for your fast answer.

These are the screenshots


img_1482
## Touch in Share




img_1483
## Touch Share to files




img_1484
## Select iCloud Drive. The file is always `GPS Exchange Format (GPX).gpx`




img_1486
## Touch on Add.




img_1487

**Comment by yoiang** [comment]
We might be seeing this: https://thomasguenzel.com/blog/2015/04/16/uiactivityviewcontroller-nsdata-with-filename/

If you don't beat me to it I'll see if that fixes the issue.

**Comment by merlos** [comment]
Cool! That did the trick: https://github.com/merlos/iOS-Open-GPX-Tracker/commit/1953f606b662f785503aaea57c1a38c6b7189e8c

**Pull request merged**
