### PR TITLE
Settings

### PR DESCRIPTION
**Pull request by geezerhiker**
Finally I pushed to the correct repository! [Xcode does not give good error messages]

I started this new branch to add a setting to the Preferences to toggle my Hiker Mode; it is complete and seems to be working.

I've attached some sample tracks and descriptions of the way they were made.

I still don't know if this pull request is the right thing to do, or who will see this stuff, but here goes.

Al

[Demo Narrative.pdf](https://github.com/merlos/iOS-Open-GPX-Tracker/files/5189980/Demo.Narrative.pdf)
[HikerModeDemos.zip](https://github.com/merlos/iOS-Open-GPX-Tracker/files/5189982/HikerModeDemos.zip)

### CODE REVIEW

**Comment by vincentneo** [comment]
why are there two pull requests now? #180 and #186? and why is this a draft pull request?

**Comment by geezerhiker** [comment]
The simple answer is that I still haven't figured out Github. I'm getting better with Git but Github makes very little sense to me.
Al

**Comment by geezerhiker** [comment]
Hi, fellas

I am experimenting with a much simpler was to accomplish my modification. So please just ignore me for awhile.

Al

**Comment by merlos** [comment]
Closing PR. Clean up

**Pull request closed without merging**
