### PR TITLE
Features/map cache

### LINKED ISSUE #74: clear cache button doesn't seem to have any effect
It appears that third party map remains even after clicking the clear cache button. 
Guess clear cache isn't working?

Not sure if this is related:
```
ERROR saving in cache: error(Cache.StorageError.deallocated)
ERROR saving in cache: value()
```
appears recursively in output console in Xcode

It appears to save though.

### PR DESCRIPTION
**Pull request by merlos**
Removed "Cache" as dependency (and CryptoSwift as it was the only pod using it)
Uses "MapCache" (http://github.com/merlos/MapCache), an specialized cache for mapping. The result is a leaner build.

The cache does not have an expiration date. If user wants to get a new version of the map he shall clear the cache using Preferences.

Also, a new feature was added. User see the Cache size, which was missing in previous version, and I personally find pretty useful.

Fixes #74 and #96

### CODE REVIEW

**Comment by vincentneo** [comment]
Have tested out the implementation, but it seems like the clearing of the maps did not fully work as intended.

I tried the following:
1. Cached a section of map based on where I am at.
2. Switch on Airplane Mode
3. Clear cache (the stored cache size is now zero)
4. Go back to map
5. Force Quit app
6. Relaunch app. (It can be seen that there is now a few tiles leftover) the cache size is now with around 100KB. 
A weird part of that, is that every clear and relaunch cycle showed a different cache size. (In my test, 119KB to 154KB to 113KB to 175KB) 

I have only tested for Open Street Map, but I assume it will be the same for all map sources.

Also, it appears when relaunching after the force quit, if I checked the preferences before the map settles down on my last location, the cache size is 0 KB.

Another thing is, if I clear cache, selected another uncached map type, force quit and relaunch, going to preferences will show 0KB, but once I click on a cached map type, like Open Street Map, go to the map, it will show some map tiles and size will be some random number in the 100KB range.

**Comment by merlos** [comment]
Thanks @vincentneo 

There are a few [unit testing that I was getting randomly right and wrong](https://github.com/merlos/MapCache/issues/4), so your findings may be related with that. 

Initially, I thought these random issues were an actual bug of the unit testing themselves due to some async operations performed wihtin, as in the resulting physical folder there were no files after clearing the cache, but, indeed, it may be a bug.

[Off topic] By the way, I created automated unit testing in MapCache using [Quick](https://github.com/Quick/Quick) and [Nimble](https://github.com/Quick/Nimble). They may be very helpful for you to test CoreGPX. Create the tests may be a bit cumbersome at the beginning but it may save you time doing boring stuff later on...

**Comment by vincentneo** [comment]
Pretty eccentric bug... Initially I thought, could it be Apple Maps caching them privately in the background?

By the way, "Cache is now empty" string introduced here should also be translated. Maybe we should get @nitricware to do translation for German language too.

> using Quick and Nimble.
Sure will take a look at these.

**Comment by nitricware** [comment]
"Cache is now empty" = "Die Cache ist jetzt leer"

**Comment by vincentneo** [comment]
Can't seem to fix this issue.... 

It seems like some tiles would suddenly come back when zooming in and out of the map. I've checked that after removing all tiles and relaunching again, the contents of the directory still seems empty.

**Comment by merlos** [comment]
Hi @vincentneo 

I figured out why the cache is not 0 after relaunching the app. It is because the OS cache. If you check the logs the app generates after relaunching the app without network you may see:

```
CachedTileOverlay:: Data received saved cacheKey=https://{s}.tile.openstreetmap.org/{z}/{x}/{y}
```
This means that the URLSession returned data to MapCache (see https://github.com/merlos/MapCache/blob/1318ef8c4f5a554161d937e92367501bea75b36b/MapCache/Classes/MapCache.swift#L59)

[URLSession](https://developer.apple.com/documentation/foundation/urlsession
) has different modes (default, ephemeral and background).  When I read about this while creating MapCache, I thought that it would be better use whatever cache the OS provides in its underlying layer... so I chose `default`.  

OSM tiles have a lifespan that is passed on the response when loaded from the server, so if the tile is in the OS cache and it has not expired, it will be returned even in offline. You can see the diagram in this link: https://developer.apple.com/documentation/foundation/nsurlrequest/cachepolicy/useprotocolcachepolicy

Also, I was checking the MapCache and I am more convinced that the issues I got in the tests are related with running asynchronous stuff... So, I would merge.

**Comment by vincentneo** [comment]
Alright then, sounds about right... Will merge.

**Pull request merged**
