### PR TITLE
Update to Swift 4.2 (only some work for the TBXML, 9 warnings)

### PR DESCRIPTION
**Pull request by EdCafferata**
Hi Merlos,
Update to Swift 4.2 (only some work for the TBXML, 9 warnings)
Hope that someone can solve the TBXML errors. 
Kind Regards, Ed Cafferata

### CODE REVIEW

**Comment by merlos** [comment]
Awesome!  Thanks Ed!

I´ll take a look during on the following days!

**Comment by merlos** [comment]
Note: this Pull request is related with issue #42

**Comment by EdCafferata** [comment]
In the NEW pull i did updated PODS and also cleaned  THE TBXML warnings.
Also changed https (title services) thinks there is some missing there.

**Comment by merlos** [comment]
Thanks again @EdCafferata. 

A couple of comments. It seems that after the pods were updated, add new files was missing.

Also I changed back the server tile URLs to have the generic https://{s}, it pools from a,b,c servers (see CachedTiledOverlay.swift)

Best, Juan.

**Comment by EdCafferata** [comment]
Yes, check did not see that :-)

The IT Crowd

Op 29 sep. 2018 om 15:58 heeft merlos <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Thanks again @EdCafferata<https://github.com/EdCafferata>.

A couple of comments. It seems that after the pods were updated, add new files was missing.

Also I changed back the server tile URLs to have the generic https://{s}, it pools from a,b,c servers (see CachedTiledOverlay.swift)

Best, Juan.

**Pull request merged**
