### PR TITLE
Allow tracking in the background on iOS9.

### PR DESCRIPTION
**Pull request by onato**
This solves the issue discussed in https://github.com/merlos/iOS-Open-GPX-Tracker/issues/18.

### CODE REVIEW

**Comment by merlos** [comment]
Hi @onato your changes look awesome. I only have to think about how comfortable I'm with moving the view stuff to IB...

Thanks for your contribution!

**Comment by raphaelschaad** [comment]
Hi! Any updates on this?

**Comment by merlos** [comment]
@raphaelschaad, I included all the changes @onato proposed in version 1.1, the only exception was to move the UI definition to a storyboard.

**Comment by raphaelschaad** [comment]
Gotcha, might be worth closing the PR then.

**Comment by merlos** [comment]
Yep!

**Pull request closed without merging**
