### PR TITLE
Trial/activity type

### PR DESCRIPTION
**Pull request by merlos**
Hi @vincentneo 

Although it is a bit advanced for a regular user I am fine with exposing the activity type to the user. 

I changed some of the activity types and added a short description for each mode to try to ease the selection.

BTW, I really like the way you used `CLActivityType+Info.swift` to display the options.

### CODE REVIEW

**Comment by merlos** [comment]
#66

**Comment by merlos** [comment]
Good point about the documentation, I forgot about it.

I will be able to do some tests of this feature next week as I´ll be traveling.

**Comment by merlos** [comment]
@vincentneo doc is now included 👍

**Comment by vincentneo** [comment]
Looking good now! Will merge.

**Pull request merged**
