### PR TITLE
Fix swiftlint build errors and a lot of warnings

### PR DESCRIPTION
**Pull request by NSMutableString**
Still 80 to go... but coming closer to 0. ;-)

### CODE REVIEW

**Comment by NSMutableString** [comment]
58 to go...

**Comment by NSMutableString** [comment]
54 to go.

**Comment by vincentneo** [comment]
@NSMutableString,
It's my first time using SwiftLint. I have reduced a little more of the issues.
I wanted to doing my part of clearing some of the mess that I did along the way 😅.

Please do correct me if I have done something wrong, by the way.

**Comment by vincentneo** [comment]
@merlos,
Now that we are down to 12 warnings, should merge or continue?

For some warnings I kinda did not want to solve the warning for the sake solving (like function body length violation by a few lines more than recommended)

For some, I don't know how to resolve.

**Comment by merlos** [comment]
Thank you guys. I had never used SwiftLint and it helps for having a better code.

PS: Sorry, it took me a while to review.

**Pull request merged**
