### PR TITLE
Recover gpx file after a crash

### PR DESCRIPTION
**Pull request by vincentneo**
Uses Core Data for this to happen.

Right now:
* Works for current trackpoints, waypoints (delete, add, edit)
* Documentations incomplete
* No alert to inform user that file 'recovery' is in progress.
* Not tested for energy impact
* track segments or other tracks not included (due to the design itself)
* Yet to undo development team settings (easier for me to debug)

What do you think? Will this be viable?

### CODE REVIEW

**Comment by merlos** [comment]
This is a good start but as you remarked in your comment the implementation of the feature requires some refinement before going to the master.

The end goal of this feature is to allow the user to recover from a crash or from an accidental close while tracking. 

The first time the app is reopened after a crash, it should ask : "Continue last session?" with two options [Cancel] and [Continue session].
    - NOTE: I think that instead of only after crash, the default behavior can ALWAYS be restore last session. User only needs to hit reset to start a new session...

- If user cancels, the app should forget whatever was saved and start fresh (same as clicking reset)

- If user decides to recover the session, it should recover the same status before it was closed in Pause mode. There are two scenarios
      1.  Last session was a fresh start.
      2. In last session, user loaded a file (for instance, "A.gpx") and continued tracking. In this scenario, whatever was in the file "A.gpx" and in the unsaved session shall be recovered. Also, if user hits save, it should prompt to save in the same file ("A.gpx").

In both cases, the map should display the extent of the loaded data. 

For the implementation, two options:

1. Keep in the CoreData DB only whatever is not saved in a file.  We only need to save the a point and the track number / segment it belongs to. It assumes the GPX file was not modified and still is on the file system. The GPX file name can be be kept in the Defaults Storage.

   ```
     CDTrackpoint {
      trackSegmentId //integer incremented each time user hits PAUSE in one session.
      trackPointId // incremented each time (== tag in your implementation, but Id is more commonly used in DB naming)
      latitude
      longitude
      elevation
      time
      name
      serialized    // A serialization of the trackPoint. 
                         // It should be easily imported using GPXTrackPoint::init(dictionary: [String : String])
                         // This should supports extended data 

}
```
Something similar for the `CDWaypoint` entity model.

2. Other option is to keep the whole loaded GPX file in the DB. This would require to have the tracks, segments and points. The only advantage of I see of this model is that it sets foundation for querying the gpx file easier for displaying stats. 
```
CDTrack {
  id
  serialized: // Serialized data. Does not include tracks. 
                  // Something that can be somewhat easily imported using GPXTrack::init(dictionary: [String : String]) {
}

CDTrackSegment {
   id
   trackId
   serialized:  //Serialized data. does not include TrackPoints elements.
}

CDTrackPoint {
   trackSegmentId
   id
   latitude
   longitude
   elevation
   time
   name
   serialized // A serialization of the point. 
                             // It should be easily imported using GPXTrackPoint::init(dictionary: [String : String]) 
```
I think first approach for solving the feature request may be simpler. And because the second model is just an extension of the first, it can be implemented in the future if necessary.

**Comment by vincentneo** [comment]
Ok. 
Have read through your comprehensive comment, and will be attempting this probably on Wednesday. 

One thing I assume I would have problems with would be the serialization part. I am not entirely sure how it could work, by `init(dictionary:)`. Will search up online to know a bit more about it.

**Comment by merlos** [comment]
How to implement is just a suggestion..., maybe you can think in better way to code it or there are some issues I have not foreseen. I like serialization because it allows to extend the data stored without changing the DB Model...

**Comment by vincentneo** [comment]
For now, I have implemented serialization by implementing `Codable` in CoreGPX, then use `JSONEncoder` to encode waypoints / trackpoints as `Data`. I hope that is good enough.

As for the recovery on start mechanism, I will do it when I have the time.

**Comment by vincentneo** [comment]
I believe most of the stuff is done, and through basic testing, seems to work.

I will test it in real life later next week, to ensure that it is working properly even with larger files. (basic debugging only with small number of data).

Will sort out merge conflict issues once approved.

Right now, only thing that isn't checked upon is the energy impact. That is something that I kinda do not know how to measure in this case.

**Comment by merlos** [comment]
You did a hard work! 👍  

Just a few things I noticed while playing around:

1. After closing the app without saving, I cannot open the app anymore. It is related with the alerts. I think we had a similar issue in the past with some alerts.
```  
019-06-17 21:00:39.416230-0400 OpenGpxTracker[11328:3935351] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x10e03d400>) of style UIAlertControllerStyleActionSheet from UIViewController (<UIViewController: 0x10dd3f7c0>). The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
*** First throw call stack:
(0x18db06ef8 0x18ccd4a40 0x1b9fadb80 0x1b9fb6bb8 0x1b9fb453c 0x1ba658800 0x1ba646840 0x1ba675b78 0x18da94b94 0x18da8f828 0x18da8fdc8 0x18da8f5b8 0x18fd03584 0x1ba64cbc8 0x100c53a98 0x18d54fb94)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

2. I am not very keen on having UI code in `CoreDataHelper`. I would say that any class in model just handles data. Anything related with UI should be managed by views and controllers. Is there any reason why we should keep it? 

3. Also, we should not forget to change Bundle Identifiers and Display Names to the final ones before making PRs. Even, I would say that change should not be committed but stashed.

4. This seems not to as expected:
   1. Start tracking
   2. Double tap and quit the app
   3. Open the app and Continue session
   4. Start tracking
   5. Double tap and quit the app
   6. Open the app and Continue session
   7. After 7 it is expected to see two segments (two lines) but only the last one is being displayed. 

4.  This crashes the app:
    1. Start tracking. Add a couple of waypoints
    2. Double tap and quit the app
    3. Open the app and Continue session
    4. Add a waypoint. 
    5. Tap over the waypoint and remove it or edit it.
    6. After 5 the app crashes.

**Comment by vincentneo** [comment]
Thanks Merlos for the encouragement!

Nice findings that you've got.

1. I believe that you have tested this on an iPad, am I right? I remember that the issue only occurs with iPad, an oversight towards this issue for me in this case, but should be an easy fix.
2. We should be able to offload that functionality to `ViewController`. 
3. Sorry! I almost always forget to stash. 
4. Very interesting bugs, will look into them when free.

**Comment by vincentneo** [comment]
It seems that the 5. issue is actually something to do with #104, with that said, I am going to add an index check before updating. 

Latest commit of this branch containing an additional function does not have that issue.

**Comment by vincentneo** [comment]
Hi @merlos,

I have done a few more commits aimed to solve the issues that you voiced out in your previous comment. Would you mind testing this pull request again?
Thank you!

**Comment by vincentneo** [comment]
Hi @merlos,

I have merged master into this pull request. 

> In general, for the future I think we should try to avoid to develop in parallel both refactors and new features as merging results more conflictive :)

I definitely won't be doing that again, as conflicts resolving at this scale is tedious. Learning it through the hard way😅.

I haven't done extensive tests, but it seems to work the same as before merge.
For now, the recovery mechanism is only for iOS, but could theoretically work for watchOS too, in future pull requests.

Also, another thing:
```swift
let url = self.applicationDocumentsDirectory.appendingPathComponent("PROJECTNAME.sqlite")
```
this line can be found in AppDelegate. Should we rename the sqlite file?
Also, I have noticed that the sqlite file can be found when using iTunes File Sharing. Should we change the directory to something else that is hides from iTunes File Sharing?

Thank you!

**Comment by merlos** [comment]
Great job @vincentneo. I also did son quick tests and everything seems to work ok 👍 .

Yeah, definitely merging conflicts after a refactor is not an straight forward task. We should try to work in features that do not modify the same files till they are merged in the master.

Regarding your other comments:

- I changed the sqllite file name to a more meaningful name.
- About the location of the sqlite file. According to[ Apple´s documentation ](
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html) if we don´t want to show it to the user we can change it to the `Library` folder, so I moved it there.

Thanks you @vincentneo!

**Pull request merged**
